spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&allowPublicKeyRetrieval=true
    username: delivery_user
    password: pwd123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 43.203.69.35
      port: 6379
      password: pwd123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

  jwt:
    secret: anlhbmdqcGFya2RpZHdvd25zcWtyd25nbWxmbHpodHBzeG1mamZxbGZlbGR0amRuZmNoc3VzdG9kamYxOTAyZmo4NGpmc2RmajA5anZ4a2NsdmJubjI0NSxtLjIzbjQ1OTh1Yjg5eGN2dWI4amtvbDI0M241bSx2OThzZDhmMAo=
    expiration: 3600000

  security:
    oauth2:
      success:
        redirect-uri: http://localhost:8080/api/v1/common
      client:
        registration:
          naver:
            client-name: naver
            client-id: 83Ln9CzHLoV9Wxis46l9
            client-secret: NtLbtD5B3j
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
              - mobile
          kakao:
            client-name: kakao
            client-id: 4c3a33797d731925ec82252b4823a084
            client-secret: xo7RG7iIKhcpGfbK1IdS5y79Rkk9dufe
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - name
              - phone_number
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE