spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&allowPublicKeyRetrieval=true
    username: delivery_user
    password: pwd123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

  jwt:
    secret: anlhbmdqcGFya2RpZHdvd25zcWtyd25nbWxmbHpodHBzeG1mamZxbGZlbGR0amRuZmNoc3VzdG9kamYxOTAyZmo4NGpmc2RmajA5anZ4a2NsdmJubjI0NSxtLjIzbjQ1OTh1Yjg5eGN2dWI4amtvbDI0M241bSx2OThzZDhmMAo=
    expiration: 3600000

logging:
  config: classpath:logback-spring.xml
#  level:
#    org.hibernate.orm.jdbc.bind: TRACE
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE

kakao:
  api:
    key: 4c3a33797d731925ec82252b4823a084